### ISSUE TITLE
Teensy 4.0 support

### ISSUE THREAD

**Issue by jasonmauer** [tonton81/TSPISlave#3]
Teensy 4.0 is here -- looks like the library will need some updating to support it. Right now there are compile errors like the following:

```
TSPISlave.cpp:54:15: error: 'IRQ_SPI0' was not declared in this scope

     spi_irq = IRQ_SPI0;
```
```
TSPISlave.cpp: In member function 'bool TSPISlave::setSlaveMISO(uint8_t)':

TSPISlave.cpp:115:38: error: 'PORT_PCR_MUX' was not declared in this scope

     CORE_PIN1_CONFIG = PORT_PCR_MUX(2);
```
```
TSPISlave.cpp: In member function 'bool TSPISlave::setSlaveMOSI(uint8_t)':

TSPISlave.cpp:141:24: error: 'PORT_PCR_DSE' was not declared in this scope

     CORE_PIN0_CONFIG = PORT_PCR_DSE | PORT_PCR_MUX(2);
```
I assume more `#ifdef`s are required to setup SPI that are specific to the Teensy 4.0 hardware. Not sure how to fix this myself as I don't know the intricacies of configuring this, unfortunately.

Any plans for supporting Teensy 4.0 in the near future?

**Comment by tonton81** [comment]
Not anytime soon, but eventually. Working on CANbus library currently until it is finalized

The SPI handling is completely different because of the different processor in teensy 4

**Comment by tonton81** [comment]
I am working on a separate version for T4

**Comment by tonton81** [comment]
SPISlave_T4 has been released.

https://github.com/tonton81/SPISlave_T4
